version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
       DATABASE_URL: ${DATABASE_URL}
       NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
       JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - .:/app                    
      - /app/node_modules          
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        npm run migrate:deploy &&
        npm run dev
      "

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: